# Remove the "-DSHOW_LOG_ERROR" to eliminate the
# verbose error logging messages generated by EZNet
CFLAGS=-g -std=gnu11 -Wall -Werror -DSHOW_LOG_ERROR

all: webserver 

webserver: webserver.c eznet.o utils.o
	$(CC) $(CFLAGS) -owebserver webserver.c eznet.o utils.o -lpthread

eznet.o: eznet.c eznet.h
	$(CC) -c $(CFLAGS) eznet.c

utils.o: utils.c utils.h
	$(CC) -c $(CFLAGS) utils.c

clean:
	rm webserver *.o

